### ISSUE TITLE
Add right-click menu functionality to the 3D editor.

### ISSUE THREAD

**Issue by IrateRedKite** [AftermathFreelancer/FLModStudio#12]
Add right-click menu functionality to the 3D editor. Would suggest using the current 'edit' menu as the template for this (excluding undo and redo). With options for:

- Cut (when object selected)
- Copy (when object selected)
- Paste (when object selected)
- Add (with context menu)
- Delete (when object selected)

Added objects could be given the pos value of the cursor at point of right click, with a 0 on the y coordinate by default.

**Comment by Lazrius** [comment]
In progress of adding these. Are there any more you can think of? Easier to add them now rather than later.

**Comment by IrateRedKite** [comment]
Not really sure there's too much more to add. Maybe a 'make template from' option?

**Comment by Lazrius** [comment]
I'll add that.
