### ISSUE TITLE
Option to disable rounding

### ISSUE THREAD

**Issue by treewyrm** [AftermathFreelancer/FLModStudio#13]
Upon saving application forcibly rounds certain numbers, particularly rotation euler angles for objects in system. Sometimes retaining float precision is necessary for objects to be aligned correctly.

**Comment by Lazrius** [comment]
I cannot properly replicate the rounding issue on the development copy, which makes me thing its what the old version (the published one) did. I will be implementing proper type validation for 1.3 that can be specified within Template.xml.

**Comment by Lazrius** [comment]
Validation now possible with bb015c3
