### ISSUE TITLE
Opinions Wanted: Do we want appearance / themeing for FLModStudio 

### ISSUE THREAD

**Issue by Lazrius** [AftermathFreelancer/FLModStudio#14]
FLModStudio was originally built with a combination of WinForms and Wpf XAML which gives us a fair bit of wiggle room for implementing proper theming support. At the base WinForms cannot do much but there are a number of different libraries that allow us implement such things without a significant degree of work.

If I were do implement this I would probably go with something like the [MaterialSkins ](https://github.com/IgnaceMaes/MaterialSkin)framework or the [MetroFramework ](https://github.com/dennismagno/metroframework-modern-ui)(or some other library if someone had a better suggestion). Is it something people want? Winforms projects in general tend to look very dated, and we cannot really use UWP without losing Windows 7 support.

**Comment by IrateRedKite** [comment]
I think if the plan is to pull FL Mod Studio up to 2020 standards, theming support would be a good step. Losing Windows 7 support would be unfortunate, but if it's going as a consequence of using UWP anyway we might as well.

**Comment by Lazrius** [comment]
If we stick to normal WinForms we can add theming with the above frameworks without losing win 7 support, but the amount of change we can do is limited. I'm happy to put in the work if it's deemed important. It's more, I guess, of an issue of whether people think the above frameworks look 'nice' or have their own suggestions.

**Comment by treewyrm** [comment]
Stick to existing, don't bother with themes. It's a development tool, not a fancy launcher, it needs to be functional and simply cover all the bases. It can have UI controls from win9x era - this does not matter as long as it's usable and sufficient to produce output data while being stable enough.

**Comment by RnScully** [comment]
I agree with treewyrm here. I generally don't think theming would help the tool. That said, this is your project, and therefore depends on your motivation. Include the parts that keep you motivated.

**Comment by CallumDev** [comment]
Theming makes the application significantly slower (especially on winforms). It's a lot of bloat for little gain. If you want the app to look consistent across 7->10 I would just suggest manually setting the colours of the built-in controls. You'll need some custom ones anyway for some more complex actions.

Also on UWP,: it sucks.
