### ISSUE TITLE
show path of current file

### ISSUE THREAD

**Issue by RnScully** [AftermathFreelancer/FLModStudio#22]
Show the path of the file you're currently working on, like in the notepad++ titlebar, where you can verify that the file you've edited is in the right directory location.

**Comment by Lazrius** [comment]
I'll address this shortly. To clarify, do you mean the name of the entire window (so "FLModStudio - C:\File\Being\Edited) or do you mean the tab at the top?

**Comment by RnScully** [comment]
Since you can open tabs in flms of many different systems, for example, possibly one from a live version, another from a dev version, and one from a vanilla install..I'd like some way in the gui to distinguish between those files. The name of the entire window is how Notepad ++ handles that issue, but I'm agnostic towards the answer. I do tend to think the name of the entire window might be the most "natural" way to do it.

**Comment by Lazrius** [comment]
Understood, I'll make the change.
