### ISSUE TITLE
Save last view layout

### ISSUE THREAD

**Issue by Polarts** [AftermathFreelancer/FLModStudio#26]
Could be useful if FLMS saved the layout of the views. Maybe even allow multiple sets, like Blender does for instance. It's really annoying to re-open the 3D view, stretch it over, and re-enable 3D models every time I want to edit a system after re-opening FLMS.

I can help make that feature if it's not on your list, although I'm probably not as experienced with WinForms. In which case, some guidence would be much appreciated :)

**Comment by Lazrius** [comment]
This is now *kind of* implemented. given how hardcoded the tool is I've done what I can. There are now options to enable these things by default, and *sometimes* the view is saved, but no idea why not all the time.
