### ISSUE TITLE
Allow the 3D editor to load models from a path set manually

### ISSUE THREAD

**Issue by IrateRedKite** [AftermathFreelancer/FLModStudio#4]
Currently Freelancer Mod Studio tries to find the solararch.ini file relative to your opened system/universe file. 

Allow it to pull the models from a pre-defined directory instead (by default `C:\Program Files (x86)\Microsoft Games\Freelancer\DATA\SOLAR`) so it's possible to work on system .ini files independently of the Freelancer directory and have the models displayed.

**Comment by Lazrius** [comment]
In the options you can set a default Freelancer data directory. If the archetype is not found relative to the system file, it will fallback on the directory placed there. If it still fails, it will fallback on user input. Is this suitable?

**Comment by IrateRedKite** [comment]
100% that's exactly what I was after when I created the issue, brilliant work.

**Comment by Lazrius** [comment]
That's actually already in the existing 1.2 version.

**Comment by IrateRedKite** [comment]
Sorry, I didn't write the issue up too clearly. Right now in 1.2, you can set the Freelancer directory, but FLMS doesn't look for the models in the 3D editor based on that path. **Regardless** of what you enter, it will look for model files relative to the location of the ini.

**Comment by Lazrius** [comment]
I cannot reproduce this. I loaded up Aftermath in the regular FLMS (which is incompatible due to our different system structure). I open up a system file and it prompts me to find the solar arch file. I closed FLMS after adding to the DATA path, then reopened it. The second time it did not prompt me.

For reference, the code does check it:
```cs
        public static string GetRelativeArchetype(string file, int fileTemplate)
        {
            return GetRelativeArchetype(Helper.Template.Data.GetDataPath(file, fileTemplate));
        }

        public static string GetRelativeArchetype(string dataPath)
        {
            if (dataPath != null)
            {
                string archetypePath = Path.Combine(dataPath, Path.Combine("Solar", "SolarArch.ini"));
                if (File.Exists(archetypePath))
                {
                    return archetypePath;
                }
            }

            return null;
        }

        // Code that loads it
        private void LoadArchetypes()
        {
            string archetypeFile = ArchetypeManager.GetRelativeArchetype(this.File, this.Data.TemplateIndex);

            // try to fallback to default DATA path
            if (archetypeFile == null)
            {
                archetypeFile = ArchetypeManager.GetRelativeArchetype(Helper.Settings.Data.Data.General.DefaultDataDirectory);

                // user interaction required to get the path of the archetype file
                if (archetypeFile == null)
                {
                    archetypeFile = this.ShowSolarArchetypeSelector();
                }
            }

            // set data path based on archetype file and not system file
            this.DataPath = Helper.Template.Data.GetDataPath(archetypeFile, Helper.Template.Data.SolarArchetypeFile);

            if (this.Archetype == null)
            {
                this.Archetype = new ArchetypeManager(archetypeFile, Helper.Template.Data.SolarArchetypeFile);
            }

            this.SetAllBlockTypes();
        }

**Comment by IrateRedKite** [comment]
Whoops, looks like I was an idiot. FLMS was grabbing my existing solararch.ini file relative to my ini files and using that. As there's no models in the mod directory, it didn't load them.

It might be worth noting somewhere that the Freelancer DATA folder path is a fallback, and that the game will first try and find a valid solararch.ini relative to whatever you're editing before using the fallback.
