### ISSUE TITLE
Change the default behavior for new/copied objects so they are added to the end of the file.

### ISSUE THREAD

**Issue by IrateRedKite** [AftermathFreelancer/FLModStudio#6]
Currently new/copied objects in FL Mod Studio are assigned a # seemingly arbitrarily or based on whatever they were copied from, which results in them being placed all over the .ini file that is being edited.

Introduce an option/behavior that causes the # assigned to new/copied objects to be the latest #+1 so that is is consistently appended to the end of the file.

**Comment by Lazrius** [comment]
New ids are assigned based on whether you have anything selected in the new window when adding/pasting. If you have nothing selected it goes at the bottom. If you have something selected it goes below that. This is default behaviour. If you would like I can add option that allows you to disable insertion at indices?

**Comment by IrateRedKite** [comment]
That would be excellent, thankyou.
