### ISSUE TITLE
Allow multiple selection and movement of grouped objects in the 3D editor.

### ISSUE THREAD

**Issue by IrateRedKite** [AftermathFreelancer/FLModStudio#7]
Allow multiple objects to be selected and moved + rotated as a group using the handles in the 3D editor. This would be particularly handy when re-positioning multi-part stations or formations of weapons platforms.

**Comment by Lazrius** [comment]
As of 13b5e12 this is possible. While it wasn't easy and has destroyed my mind slightly in the process, it's working for the most part. You can select multiple elements by holding control and click them in the table view or system viewer.

The maths mostly holds up, but if you drag too many objects at once, in a large space, the engine gets a bit confused and doesn't know where to put some of them. Don't know what the limit is, but I managed to move about 20 base parts without them getting unaligned, but it's something to consider. 

Other thing is the the bounding box only updates to one object at a time. When you use shift to select multiple objects in the table view it will put a box around the last one selected. If you use cntl + click in system/table view it will only show the first one you selected.
