### ISSUE TITLE
Custom Object/Zone Templates

### ISSUE THREAD

**Issue by IrateRedKite** [AftermathFreelancer/FLModStudio#8]
It would be extremely useful to have an option for custom object+ zone templates with pre-filled properties defined by the user.

I would suggest that the edit/add dialogue be used to create these with a 'new template' option leading to a form-style window where the user can define the defaults for their custom object.

**Comment by Lazrius** [comment]
This is now implemented with bfd51a6. A couple of notes worth mentioning for later. As it stands the template menu when used for the first time will require a restart after adding the first template, and you can't paste a template into a document that already has another entry with the same nickname as the template.
