### ISSUE TITLE
Allow customization of colors in the 3D Editor

### ISSUE THREAD

**Issue by IrateRedKite** [AftermathFreelancer/FLModStudio#9]
Right now zone and object colors in the 3D editor are defined by the zone/object type. 

Please make it possible to change these colors in the options, as it would be extremely beneficial for visually impaired users (particularly those of us who are red/green color blind) as some of the default colors in the editor can make telling zones apart particularly difficult (A good example for me would be ZoneVignette and ZoneSphereExclusion)

**Comment by Lazrius** [comment]
This is done now. I added some lines that should cause it to update after editing it in the settings, but you may need to refresh the system file (maybe, didn't test it).
